<?php

/**
* CLASE PARA FILTRA
*/

class Filtro {

	private $test = '';
	private $resultado = array();

	public function __construct(){
		
		$this->test = '{"INFOUNIDAD": [{"UNIDAD":"099027","TIPO_VEHICULO":"FO05","DESC_TIPO_VEH":"FORTUNER 4X4 T\/A T DSL. INTERCOOLER","COLOR_EXTERNO":"1C0","DESC_COLOR_EXT":"SILVER MEDIUM","MODELO":"2011","UBICACION":"141","DESC_UBICACION":"Centro Exhibici\u00f3n CT","FECHA_LLEGADA":"23\/12\/2010 1:42:16 PM","EQUIPAMIENTO":"N","EXTRAS_INSTALADAS":"N","NOTAS":"Unidad Blindada\n\nPamela Q.\n","CLIENTE":"117060","NOMBRE_CLIENTE":"PURDY MOTOR SA - EXTRAS","ESTADO":"S","SUCURSAL":"DISTRIBUIDOR","VENDEDOR":"1024","NOMBRE_VENDEDOR":"Pamela Quesada Sancho"},{"UNIDAD":"100103","TIPO_VEHICULO":"LHB6","DESC_TIPO_VEH":"HIACE 15 PASAJEROS DIESEL SEMIFULL","COLOR_EXTERNO":"058","DESC_COLOR_EXT":"BLANCO","MODELO":"2011","UBICACION":"074","DESC_UBICACION":"Purdy Trabajo - Ciudad Toyota","FECHA_LLEGADA":"13\/12\/2010 7:53:28 AM","EQUIPAMIENTO":"N","EXTRAS_INSTALADAS":"N","NOTAS":{},"CLIENTE":"117939","NOMBRE_CLIENTE":"DEMO PURDY TRABAJO","ESTADO":"S","SUCURSAL":"PTRABAJO","VENDEDOR":"166","NOMBRE_VENDEDOR":"Allan Rodr\u00edguez Fern\u00e1ndez"},{"UNIDAD":"100403","TIPO_VEHICULO":"PV16","DESC_TIPO_VEH":"PRADO TDI PLATINUM VX TA","COLOR_EXTERNO":"1F7","DESC_COLOR_EXT":"Silver Metalico","MODELO":"2011","UBICACION":"141","DESC_UBICACION":"Centro Exhibici\u00f3n CT","FECHA_LLEGADA":"23\/12\/2010 1:41:39 PM","EQUIPAMIENTO":"N","EXTRAS_INSTALADAS":"N","NOTAS":{},"CLIENTE":"112321","NOMBRE_CLIENTE":"PURDY MOTOR SOCIEDAD ANONIMA-MERCADEO","ESTADO":"S","SUCURSAL":"DISTRIBUIDOR","VENDEDOR":"2011","NOMBRE_VENDEDOR":"Isabel M\u00e9ndez Alvarado"},{"UNIDAD":"101547","TIPO_VEHICULO":"FJ10","DESC_TIPO_VEH":"FJ T\/A 4.0 GASOLINA","COLOR_EXTERNO":"2JX","DESC_COLOR_EXT":"ROJO LADRILLO CON TECHO BLANCO","MODELO":"2011","UBICACION":"054","DESC_UBICACION":"Entrega Sucursal Paseo Colon","FECHA_LLEGADA":"14\/04\/2011 12:23:21 PM","EQUIPAMIENTO":"N","EXTRAS_INSTALADAS":"N","NOTAS":{},"CLIENTE":"133052","NOMBRE_CLIENTE":"DISTRIBUIDOR USADOS","ESTADO":"S","SUCURSAL":"PCUSADOS","VENDEDOR":"1005","NOMBRE_VENDEDOR":"Isaac Jim\u00e9nez Morera"},{"UNIDAD":"102469","TIPO_VEHICULO":"4R13","DESC_TIPO_VEH":"4 Runner Superfull  ","COLOR_EXTERNO":"1F7","DESC_COLOR_EXT":"Silver Metalico","MODELO":"2012","UBICACION":"079","DESC_UBICACION":"Pre Entrega CT3","FECHA_LLEGADA":"04\/08\/2011 12:00:00 AM","EQUIPAMIENTO":"N","EXTRAS_INSTALADAS":"N","NOTAS":{},"CLIENTE":"112321","NOMBRE_CLIENTE":"PURDY MOTOR SOCIEDAD ANONIMA-MERCADEO","ESTADO":"S","SUCURSAL":"DISTRIBUIDOR","VENDEDOR":"206","NOMBRE_VENDEDOR":"Paula Lucas Cambronero "},{"UNIDAD":"102555","TIPO_VEHICULO":"BE03","DESC_TIPO_VEH":"TERIOS BEEGO 4X4 T\/M SUPERFULL","COLOR_EXTERNO":"W23","DESC_COLOR_EXT":"BLANCO","MODELO":"2011","UBICACION":"079","DESC_UBICACION":"Pre Entrega CT3","FECHA_LLEGADA":"17\/05\/2011 8:31:55 AM","EQUIPAMIENTO":"N","EXTRAS_INSTALADAS":"N","NOTAS":{},"CLIENTE":"0069817","NOMBRE_CLIENTE":"MARIA DE LOS ANGELES RODRIGUEZ TORRES","ESTADO":"S","SUCURSAL":"DISTRIBUIDOR","VENDEDOR":"4","NOMBRE_VENDEDOR":"Fernando Par\u00eds Coronado"},{"UNIDAD":"102568","TIPO_VEHICULO":"IN10","DESC_TIPO_VEH":"INNOVA","COLOR_EXTERNO":"1C0","DESC_COLOR_EXT":"SILVER MEDIUM","MODELO":"2011","UBICACION":"025","DESC_UBICACION":"Pr\u00e9stamo","FECHA_LLEGADA":"27\/04\/2011 2:04:42 PM","EQUIPAMIENTO":"N","EXTRAS_INSTALADAS":"N","NOTAS":{},"CLIENTE":"0081593","NOMBRE_CLIENTE":"KAREN SAENZ ARGUELLO","ESTADO":"S","SUCURSAL":"DISTRIBUIDOR","VENDEDOR":"1048","NOMBRE_VENDEDOR":"Anielka Cantillano Chavez"},
{"UNIDAD":"102569","TIPO_VEHICULO":"IN20","DESC_TIPO_VEH":"INNOVA","COLOR_EXTERNO":"1C0","DESC_COLOR_EXT":"SILVER MEDIUM","MODELO":"2011","UBICACION":"025","DESC_UBICACION":"Pr\u00e9stamo","FECHA_LLEGADA":"27\/04\/2011 2:04:42 PM","EQUIPAMIENTO":"N","EXTRAS_INSTALADAS":"N","NOTAS":{},"CLIENTE":"0081593","NOMBRE_CLIENTE":"KAREN SAENZ ARGUELLO","ESTADO":"S","SUCURSAL":"DISTRIBUIDOR","VENDEDOR":"1048","NOMBRE_VENDEDOR":"Anielka Cantillano Chavez"},{"UNIDAD":"102897","TIPO_VEHICULO":"GM10","DESC_TIPO_VEH":"GRAN MAX","COLOR_EXTERNO":"W09","DESC_COLOR_EXT":"BLANCO","MODELO":"2012","UBICACION":"017","DESC_UBICACION":"Exhibici\u00f3n Mercadeo","FECHA_LLEGADA":"13\/07\/2011 12:00:00 AM","EQUIPAMIENTO":"N","EXTRAS_INSTALADAS":"N","NOTAS":{},"CLIENTE":"117939","NOMBRE_CLIENTE":"DEMO PURDY TRABAJO","ESTADO":"S","SUCURSAL":"PTRABAJO","VENDEDOR":"166","NOMBRE_VENDEDOR":"Allan Rodr\u00edguez Fern\u00e1ndez"},{"UNIDAD":"103045","TIPO_VEHICULO":"YA20","DESC_TIPO_VEH":"YARIS SEDAN 1.5 T\/M ( L.N.)","COLOR_EXTERNO":"8R3","DESC_COLOR_EXT":"AZUL GRISACEO","MODELO":"2012","UBICACION":"079","DESC_UBICACION":"Pre Entrega CT3","FECHA_LLEGADA":"04\/08\/2011 12:00:00 AM","EQUIPAMIENTO":"N","EXTRAS_INSTALADAS":"N","NOTAS":{},"CLIENTE":"0000029","NOMBRE_CLIENTE":"ALVARO RAMOS RECHNITZ","ESTADO":"S","SUCURSAL":"DISTRIBUIDOR","VENDEDOR":"2166","NOMBRE_VENDEDOR":"Alex Alens Quesada"},{"UNIDAD":"103297","TIPO_VEHICULO":"BE11","DESC_TIPO_VEH":"TERIOS BEGO PAQ. ESPECIAL 4X2 M\/T ","COLOR_EXTERNO":"S33","DESC_COLOR_EXT":"GRIS METALICO","MODELO":"2012","UBICACION":"079","DESC_UBICACION":"Pre Entrega CT3","FECHA_LLEGADA":"09\/09\/2011 5:11:58 PM","EQUIPAMIENTO":"N","EXTRAS_INSTALADAS":"N","NOTAS":{},"CLIENTE":"112321","NOMBRE_CLIENTE":"PURDY MOTOR SOCIEDAD ANONIMA-MERCADEO","ESTADO":"S","SUCURSAL":"DISTRIBUIDOR","VENDEDOR":"206","NOMBRE_VENDEDOR":"Paula Lucas Cambronero "},{"UNIDAD":"103298","TIPO_VEHICULO":"BE12","DESC_TIPO_VEH":"TERIOS BEGO PAQ. ESPECIAL 4X4 M\/T","COLOR_EXTERNO":"S28","DESC_COLOR_EXT":"SILVER METALIC","MODELO":"2012","UBICACION":"079","DESC_UBICACION":"Pre Entrega CT3","FECHA_LLEGADA":"09\/09\/2011 5:11:58 PM","EQUIPAMIENTO":"N","EXTRAS_INSTALADAS":"N","NOTAS":{},"CLIENTE":"112321","NOMBRE_CLIENTE":"PURDY MOTOR SOCIEDAD ANONIMA-MERCADEO","ESTADO":"S","SUCURSAL":"DISTRIBUIDOR","VENDEDOR":"206","NOMBRE_VENDEDOR":"Paula Lucas Cambronero "} ]}';
	
		//$this->test = '{"a":1,"b":2,"c":3,"d":4,"e":5}';
		//$this->test = json_encode($this->test);
	}

	/**
	* FILTRAR JSON
	* @param $campo -> campo a filtrar
	* @param $valor -> valor a comparar
	* @param <json> $datos
	*/
	public function Filtrar($campo, $valor){
		
		$resultados = array();
		$datos = json_decode( $this->test, true );
		
		//var_dump($datos);
		
		foreach( $datos['INFOUNIDAD'] as $fila => $value ){
			
			if( is_array($value)){
				foreach ($value as $f => $c) {
					echo $fila.' | '.$f.'=>'. $c. '<br/>';
					
					if( $campo == $f && $valor == $c){
						$resultados[] = $value;
					}
				}
			}
		}

		echo '<hr><pre>';

		print_r($resultados);

		echo '</pre>';
	}

}

$filtrar = new Filtro();

$filtrar->Filtrar('TIPO_VEHICULO', 'YA20');

?>